[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Serve the static HTML file for the home page
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle client-side routing for Next.js for all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200